services:
  pocketbase:
    build:
      context: ./pocketbase
    networks:
      - lan
    labels:
      traefik.enable: true
      traefik.http.services.pocketbase.loadbalancer.server.port: 8080
      traefik.http.routers.pocketbase-https.rule: Host(`${SERVER_NAME}`)
      traefik.http.routers.pocketbase-https.entrypoints: https
      traefik.http.routers.pocketbase-https.service: pocketbase

networks:
  lan:
    external: true