name: feedbacks

packages:
  - packages/**
  - exemple

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    environment:
      sdk: 3.5.2
      flutter: 3.24.2
    # dependencies:
    #   dio: ^5.7.0
    #   equatable: ^2.0.5
    #   firebase_remote_config: ^5.0.4
    #   freezed_annotation: ^2.4.4
    #   json_annotation: ^4.9.0
    # dev_dependencies:
    #   build_runner: ^2.4.12
    #   freezed: ^2.5.7
    #   json_serializable: ^6.8.0
    #   mocktail: ^1.0.4
    #   test: ^1.25.2
  clean:
    hooks:
      post: rm pubspec.lock

scripts:
  generate:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.